export const navLinks = [
  {
    path: "/",
    name: "About",
  },
  {
    path: "/projects",
    name: "Projects",
  },
  {
    path: "/hackathons",
    name: "Hacks",
  },
];

export const notableAchievements = [
  {
    title: "Smart India Hackathon",
    body: [
      { text: "Made it to " },
      { text: "SIH 2025", bold: true },
      {
        text: " in my 3rd semester of college. Didn't really know what I was doing but figured it out.",
      },
    ],
  },
  {
    title: "Hackathons",
    body: [
      { text: "Won " },
      { text: "3 hackathons", bold: true, href: "/hackathons" },
      { text: ", mostly building AI stuff. " },
      { text: "Gray Matter", bold: true },
      {
        text: " is probably the one I'm proudest of, an AI-powered browser extension built for neurodivergent individuals and students who find the modern web overwhelming. It uses ",
      },
      { text: "local LLMs", bold: true },
      {
        text: ", layout parsing, and accessibility-first design to reduce distractions, simplify content, and ease visual focus. Took home ",
      },
      { text: "Rs. 20,000", bold: true },
      { text: " at " },
      { text: "Navkis College of Engineering", bold: true },
      { text: "." },
    ],
  },
  {
    title: "Startup Qualifier",
    body: [
      { text: "Selected and qualified for a " },
      { text: "national-level startup event", bold: true },
      { text: " hosted by " },
      { text: "CEDAT", bold: true },
      { text: " and " },
      { text: "0x.day", bold: true },
      { text: " at " },
      { text: "RV College", bold: true },
      { text: "." },
    ],
  },
  {
    title: "Side project at scale",
    body: [
      { text: "Built " },
      { text: "Kamanime", bold: true },
      { text: ", an anime streaming site, hit around " },
      { text: "5,000 users", bold: true },
      { text: " and was handling " },
      { text: "100 concurrent viewers", bold: true },
      { text: " at peak using web scraping and some creative infra decisions. Had to take it down after a DMCA." },
    ],
  },
];

export const intros = [
  "Software Engineer",
  "Graphic Designer",
  "Web Developer",
  "Problem Solver",
  "Creative Thinker",
  "Coffee Addict",
  "Tech Geek",
];

export const experiences = [
  {
    role: "Software Developer Intern",
    year: "Feb 2024 - Sept 2024",
    company: "GITCS.",
    type: "Internship",
    location: "Guwahati, On-Site",
    logo: "/Company/gitcs.png",
    responsibility: [
      [
        { text: "Developed " },
        { text: "websites and systems", bold: true },
        { text: " for clients and maintained existing platforms." },
      ],
    ],
    techstacks: ["ReactJS", "NextJS", "Frame Motion", "ThreeJS"],
  },
  {
    role: "Software Engineer",
    year: "Oct 2024 - Jan 2025",
    company: "TTIPL",
    type: "Full-Time",
    location: "Hyderabad, Hybrid",
    logo: "/Company/ttipl.png",
    responsibility: [
      [
        { text: "Built " },
        { text: "internal ERP modules", bold: true },
        {
          text: " for billing, vendor, and project tracking used by construction operations.",
        },
      ],
      [
        { text: "Developed " },
        { text: "semantic project document search", bold: true },
        { text: " using " },
        {
          text: "RAG pipelines with OpenAI embeddings and vector databases",
          bold: true,
        },
        { text: " for construction drawings, BOQs, and reports." },
      ],
      [
        { text: "Optimized " },
        { text: "API performance and database queries", bold: true },
        { text: " improving internal tool response times and reliability." },
      ],
    ],
    techstacks: [
      "ReactJS",
      "NextJS",
      "Tailwindcss",
      "Prisma",
      "Supabase",
      "OpenAI",
      "Pinecone",
      "Node.js",
    ],
  },
  {
    role: "Founding Engineer",
    year: "Jan 2025 - July 2025",
    company: "Navdyut AI",
    type: "Full-Time",
    location: "Guwahati, On-Site",
    logo: "/Company/Navdyut.png",
    responsibility: [
      [
        { text: "Got deep into " },
        {
          text: "fine-tuning LLMs on low-resource Indian languages",
          bold: true,
        },
        { text: " using " },
        { text: "Unsloth", bold: true },
        { text: ", " },
        { text: "containerizing models with Docker", bold: true },
        { text: ", self-hosting them on servers, and exposing them as " },
        { text: "public APIs", bold: true },
        { text: "." },
      ],
      [
        { text: "Used the " },
        { text: "Brave Search API", bold: true },
        { text: " to give the bot " },
        { text: "real-time information", bold: true },
        { text: " from the web." },
      ],
      [
        { text: "Scaled the system to " },
        { text: "500+ users", bold: true },
        { text: " and contributed to deployments for " },
        { text: "public sector", bold: true },
        { text: " use." },
      ],
      [
        { text: "Project work was featured in " },
        { text: "regional newspapers", bold: true },
        { text: "." },
      ],
    ],
    techstacks: [
      "Mistral",
      "Unsloth",
      "Docker",
      "Langchain",
      "LlamaIndex",
      "Pinecone",
      "NextJS",
      "Tailwindcss",
      "Supabase",
      "Drizzle",
    ],
  },
  {
    role: "Applied AI Engineer",
    year: "July 2025 - Present",
    company: "Bez",
    type: "Full-Time",
    location: "New York, Remote",
    logo: "/Company/Astra.png",
    logoPadding: false,
    invertLogo: true,
    responsibility: [
      [
        {
          text: "Reduced jewelry design turnaround from days to minutes by building AI agent workflows using ",
        },
        { text: "Vercel AI SDK", bold: true },
        { text: " with observability via " },
        { text: "Langfuse", bold: true },
        { text: "." },
      ],
      [
        { text: "Built an interactive jewelry design canvas using " },
        { text: "React + XYFlow", bold: true },
        {
          text: " enabling credit-gated editing and real-time agent-driven design iteration.",
        },
      ],
      [
        { text: "Developed a " },
        { text: "Redis", bold: true },
        { text: " queue pipeline generating " },
        { text: "70+ product images", bold: true },
        { text: " per client batch in " },
        { text: "under 5 minutes", bold: true },
        { text: "." },
      ],
      [
        { text: "Built a " },
        { text: "multimodal inventory search", bold: true },
        {
          text: " enabling queries by image or text, both vectorized and ranked against a ",
        },
        { text: "Milvus", bold: true },
        { text: " DB via " },
        { text: "cosine similarity", bold: true },
        { text: " with " },
        { text: "AI image tagging", bold: true },
        { text: " to enrich retrieval. Achieved " },
        { text: "sub-1.5s", bold: true },
        { text: " search across " },
        { text: "25,000+ images", bold: true },
        { text: " using " },
        { text: "gemini-embedding-2-preview", bold: true },
        { text: " and a " },
        { text: "semantic reranker", bold: true },
        { text: "." },
      ],
      [
        { text: "Built a " },
        { text: "RAG-based persistent memory system", bold: true },
        { text: " using " },
        { text: "user-scoped vector embeddings", bold: true },
        { text: " in " },
        { text: "Milvus", bold: true },
        {
          text: " to continuously learn and refine personalized jewelry design preferences across sessions. Optimized ",
        },
        { text: "ANN-based embedding retrieval to sub-80ms", bold: true },
        { text: " latency" },
      ],
      [
        { text: "Used " },
        { text: "General Translation", bold: true },
        { text: " to ship " },
        { text: "multilingual app experiences", bold: true },
        { text: " for " },
        { text: "international clients", bold: true },
        { text: "." },
      ],
      [
        {
          text: "Improved reliability and performance across microservices deployed with ",
        },
        { text: "Docker", bold: true },
        { text: ", " },
        { text: "Firebase", bold: true },
        { text: ", and " },
        { text: "GCP", bold: true },
        { text: "." },
      ],
      [
        { text: "Deployed multiple services on " },
        { text: "Cloud Run", bold: true },
        { text: " with end-to-end " },
        { text: "CI/CD", bold: true },
        { text: " pipelines managed via " },
        { text: "Coolify", bold: true },
        { text: "." },
      ],
    ],
    techstacks: [
      "Vercel AI SDK",
      "React",
      "XYFlow",
      "Redis",
      "Firebase",
      "GCP",
      "Docker",
      "Langfuse",
      "NextJS",
    ],
  },
];

export const projects = [
  {
    title: "Gray Matter",
    category: "Hackathon · Browser Extension",
    description:
      "An AI-powered Chrome extension designed for neurodivergent individuals and students who find the modern web overwhelming. Leverages local LLMs, layout parsing, and accessibility-first design to reduce distractions, simplify content, and ease visual focus.",
    techstacks: ["WXT", "React", "Tailwind CSS", "Shadcn UI", "WebLLM", "Local LLMs"],
    status: "active",
    link: "https://github.com/karmatheHacker/gray-matter",
    preview: "/projects/graymatter.png",
    github: "karmatheHacker/gray-matter",
  },
  {
    title: "Fluey AI",
    category: "Hackathon · Mobile App",
    description:
      "A React Native AI chat application focused on experience quality — featuring real-time streaming responses, markdown and LaTeX math rendering, skeleton loading states, persistent chat sessions via AsyncStorage, and smooth screen transitions. Powered by OpenRouter and Gemini APIs. Won 1st place at AI IGNITE.",
    techstacks: ["React Native", "Expo", "TypeScript", "Zustand", "OpenAI"],
    status: "active",
    link: "https://github.com/Neel2107/fluey-ai",
    preview: "/projects/fluey-ai.png",
    github: "Neel2107/fluey-ai",
  },
  {
    title: "Kamanime",
    category: "Side Project · Web App",
    description:
      "An anime streaming and tracking platform that uses torrents under the hood for downloading and streaming — no third-party CDN required. Sync your AniList, track progress, discover new titles, and stream directly in the browser with a clean, community-driven UI.",
    techstacks: ["React", "Vite", "Convex", "Tailwind CSS", "HLS.js", "Clerk"],
    status: "active",
    link: "https://github.com/karmatheHacker/kamanime",
    preview: "/projects/kamanime.png",
    github: "karmatheHacker/kamanime",
  },
  {
    title: "Wellbeing",
    category: "Side Project · Mobile App",
    description:
      "A comprehensive healthcare mobile app featuring AI-powered symptom analysis, doctor discovery, appointment booking, virtual consultations via WebRTC video calling, and offline-first database sync for instant messaging.",
    techstacks: [
      "React Native",
      "TypeScript",
      "WebRTC",
      "Firebase",
      "Socket.IO",
      "WatermelonDB",
    ],
    status: "active",
    link: "https://github.com/karmatheHacker/Wellbeing",
    preview: "/projects/wellbeing.png",
    github: "karmatheHacker/Wellbeing",
  },
];


export const hackathons = [
  {
    title: "Gray Matter",
    event: "HACKLOOM",
    year: "2026",
    placement: "1st Place",
    college: "Navkis College of Engineering",
    body: [
      { text: "Built Gray Matter, a Chrome Extension designed for " },
      { text: "neurodivergent individuals and students", bold: true },
      { text: " who find the modern web overwhelming. It leverages " },
      { text: "local Large Language Models (LLMs)", bold: true },
      { text: ", advanced layout parsing, and accessibility-first design to " },
      { text: "reduce distractions", bold: true },
      { text: ", simplify complex layout, and ease visual focus." },
    ],
    techstacks: [
      "WXT",
      "React",
      "Tailwind CSS",
      "Shadcn UI",
      "WebLLM",
      "Local LLMs",
    ],
    link: "https://github.com/karmatheHacker/gray-matter",
  },
  {
    title: "SentinelAI",
    event: "INOVIX",
    year: "2026",
    placement: "2nd Place",
    college: "Rajeev Institute of Technology",
    body: [
      { text: "Built " },
      { text: "SentinelAI", bold: true },
      { text: ", an adaptive, " },
      { text: "context-aware API Security Firewall", bold: true },
      {
        text: " designed as an intelligent middleware layer between clients and backend systems. It ",
      },
      { text: "silently intercepts and neutralizes malicious requests", bold: true },
      {
        text: " before they reach application logic — handling prompt injection, credential stuffing, anomalous payloads, and abuse patterns in real time. Not just a hackathon project. A problem the industry faces. A solution the industry needs, and ",
      },
      { text: "one worth building", bold: true },
      { text: ". Placed " },
      { text: "2nd on the leaderboard", bold: true },
      { text: "." },
    ],
    techstacks: ["Node.js", "Express", "Python", "OpenAI", "Redis"],
    link: "https://github.com/rabinkrrai/SentinelAI",
  },
  {
    title: "Fluey AI",
    event: "AI IGNITE",
    year: "2024",
    placement: "1st Place",
    college: "Assam Engineering College",
    body: [
      { text: "Built " },
      { text: "Fluey AI", bold: true },
      { text: ", a " },
      { text: "React Native AI chat application", bold: true },
      {
        text: " with a focus on experience quality — not just functionality. Implemented ",
      },
      { text: "real-time streaming responses", bold: true },
      { text: ", " },
      { text: "markdown and LaTeX math rendering", bold: true },
      { text: ", skeleton loading states, " },
      { text: "persistent chat sessions", bold: true },
      {
        text: " via AsyncStorage, and smooth screen transitions using Reanimated. Powered by ",
      },
      { text: "OpenRouter and Gemini APIs", bold: true },
      {
        text: " with Zustand for state. The polish and depth of the UX secured ",
      },
      { text: "1st place at AI IGNITE", bold: true },
      { text: "." },
    ],
    techstacks: ["React Native", "Expo", "TypeScript", "Zustand", "OpenAI"],
    link: "https://github.com/Neel2107/fluey-ai",
  },
  {
    title: "Wellbeing",
    event: "TECHNOVATE Project Expo",
    year: "2026",
    placement: "2nd Place",
    college: "Assam Engineering College",
    body: [
      { text: "Secured " },
      { text: "2nd position at TECHNOVATE", bold: true },
      { text: " by building Wellbeing, a healthcare mobile app featuring " },
      { text: "AI-powered symptom analysis", bold: true },
      { text: ", doctor discovery, appointment booking, and " },
      { text: "real-time video consultations via WebRTC", bold: true },
      { text: " with an " },
      { text: "offline-first database sync", bold: true },
      { text: " for instant messaging." },
    ],
    techstacks: [
      "React Native",
      "TypeScript",
      "WebRTC",
      "Firebase",
      "WatermelonDB",
      "Socket.IO",
    ],
    link: "https://github.com/karmatheHacker/Wellbeing",
  },
  {
    title: "Gray Matter",
    event: "PRAYOG",
    year: "2026",
    placement: "2nd Place",
    college: "Navkis College of Engineering",
    body: [
      { text: "Showcased the same project, " },
      { text: "Gray Matter", bold: true },
      { text: ", at " },
      { text: "PRAYOG Project Expo", bold: true },
      { text: " and secured " },
      { text: "2nd place on the leaderboard", bold: true },
      {
        text: ". Demonstrated live local LLM inference, distraction-free reading modes, and real-time layout simplification running fully offline in the browser.",
      },
    ],
    techstacks: [
      "WXT",
      "React",
      "Tailwind CSS",
      "Shadcn UI",
      "WebLLM",
      "Local LLMs",
    ],
    link: "https://github.com/karmatheHacker/gray-matter",
  },
  {
    title: "Smart India Hackathon",
    event: "SIH 2025",
    year: "2025",
    placement: "Qualifier",
    college: "",
    body: [
      { text: "Qualified for " },
      { text: "SIH 2025", bold: true },
      { text: " in my " },
      { text: "3rd semester", bold: true },
      {
        text: " of college. Figured it out on the fly and made it through the ",
      },
      { text: "national rounds", bold: true },
      { text: "." },
    ],
    techstacks: [],
    link: "https://github.com/rabinkrrai/sih-2025",
  },
  {
    title: "National Startup Pitch",
    event: "CEDAT & 0x.day",
    year: "2025",
    placement: "Qualifier",
    college: "RV College",
    body: [
      { text: "Selected and qualified for a " },
      { text: "national-level startup competition", bold: true },
      { text: " hosted by " },
      { text: "CEDAT", bold: true },
      { text: " and " },
      { text: "0x.day", bold: true },
      { text: " at " },
      { text: "RV College", bold: true },
      {
        text: ". Pitched the feasibility, product-market fit, and technical design of an offline payment application built using ",
      },
      { text: "UPI123PAY (*99#)", bold: true },
      { text: " to industry veterans. Redesigned a tedious " },
      { text: "10+ step flow down to just 3 simple steps", bold: true },
      { text: " to help users send payments securely without internet access." },
    ],
    techstacks: [],
    link: "https://github.com/rabinkrrai/startup-pitch",
  },
];

export const research = [
  {
    title:
      "PolySpeech-HS: Multilingual Non-Autoregressive Text-to-Speech Synthesis with Hidden-State Adapters",
    category: "Speech Synthesis & Multilingual AI",
    description:
      "A non-autoregressive text-to-speech (TTS) multilingual synthesis framework designed to address the linguistic diversity and real-time deployment challenges of Indian languages. By deploying a unified encoder-decoder architecture paired with lightweight hidden-state adapters, PolySpeech-HS enables efficient cross-lingual generalization while preserving language-specific prosodic nuances. Achieved state-of-the-art performance with MOS of 4.30, MCD of 4.7 dB, and RTF of 0.13 across six Indian languages.",
    techstacks: [
      "TTS",
      "Non-Autoregressive",
      "Hidden-State Adapters",
      "Multilingual AI",
      "Indian Languages",
      "AMO-HSA",
    ],
    status: "under-review",
    link: "#",
    journal: "IEEE Transactions on Audio, Speech and Language Processing",
    year: "2025",
    collaboration: "Vellore Institute of Technology",
  },
  {
    title:
      "A Novel Data-Centric Transformer Fine-Tuning: A Modular Framework for Rapid Domain Adaptation and Deployment",
    category: "Large Language Models & Domain Adaptation",
    description:
      "A data-centric, hardware-light workflow for fine-tuning transformers that sidesteps costly LLM APIs. Automatically scrapes high-signal web content and converts it into Q&A pairs to fine-tune a GPT-2-Medium model (355M parameters) in ~7 minutes on a single RTX-3060. Achieves 67.3% accuracy (+34% over base model) with 1.4s median latency and zero inference cost.",
    techstacks: [
      "GPT-2",
      "LoRA",
      "8-bit Adam",
      "Domain Adaptation",
      "Next.js",
      "Q&A Generation",
      "Fine-tuning",
    ],
    status: "under-review",
    link: "#",
    journal: "IEEE Transactions on Computational Social Systems",
    year: "2025",
    collaboration: "Vellore Institute of Technology",
  },
  {
    title:
      "Fine-Tuning Mistral 22B: The First Large Language Model for Assamese Language Tasks",
    category: "Low-Resource Language Processing",
    description:
      "The first fine-tuned Large Language Model specifically engineered for Assamese, a low-resource Indo-Aryan language spoken by approximately 15 million individuals. Introduces AssamText-750K dataset and custom Unicode mapping system exclusively for Assamese. This pioneering work becomes the first and only Assamese LLM backed by language-specific Unicode infrastructure, achieving 20% average improvement across text generation fluency, sentiment analysis accuracy, and Assamese-to-English translation quality.",
    techstacks: [
      "Mistral 22B",
      "LoRA",
      "Unicode Mapping",
      "Assamese NLP",
      "Low-Resource Languages",
      "AssamText-750K",
    ],
    status: "under-review",
    link: "#",
    journal: "IEEE Transactions on Neural Networks and Learning Systems",
    year: "2025",
    collaboration: "Vellore Institute of Technology",
  },
];
